### ISSUE TITLE
Can't install; need "setuptools"

### ISSUE THREAD

**Issue by starun96** [oddProton/dynpaper#12]
I'm trying to install the program, but it's not allowing me. After I type `./setup.py install`, it gives me the error: `No module named 'setuptools'`. How do I download setuptools?

**Comment by oddProton** [comment]
You have to install them through a package manager. It usually comes installed on most distros,

sudo apt-get install -y python-setuptools

**Comment by starun96** [comment]
So I got it to work after doing: sudo apt install python3-pip (installing pip3 because I didn't already have it) pip3 install setuptools (installing setuptools) sudo ./setup.py install (installing the setup with sudo)
