### ISSUE TITLE
Limiting number of image files to 17

### ISSUE THREAD

**Issue by Aaron-Macneill** [oddProton/dynpaper#2]
Rather than having the number of wallpapers set at 17, perhaps you could try crawling a specified directory for image files.

And then instead of forcing a format of {number}.jpg maybe it'd work best by sorting files alphabetically.

**Comment by oddProton** [comment]
The whole idea is that the wallpapers are changing based on the time of the day and Apple provided only 17 wallpapers.

I am planning on making it so one can specify that the first let’s say 20 wallpapers are for dawn to dusk and the next 30 for dusk to dawn.

No clue however how this can be done with varying names.

**Comment by oddProton** [comment]
Dealt with as of v1.1.1 .
