### ISSUE TITLE
Fails to run ./setup.py

### ISSUE THREAD

**Issue by WaseemAlkurdi** [oddProton/dynpaper#4]
I forked the repo, but upon running 
``` ./setup.py install ```
I get the following output:
```
waseem@my-awesome-slabtop:~/dynpaper$ ./setup.py install
Traceback (most recent call last):
  File "./setup.py", line 6, in <module>
    from setuptools import setup
ImportError: No module named setuptools
```

**Comment by WaseemAlkurdi** [comment]
My stupidity; I thought that ```python-setuptools``` was installed, it turns out ```dpkg``` didn't configure the package.

**Comment by oddProton** [comment]
Thanks for noting it, I will add it to troubleshooting.
